### ISSUE TITLE
Bug: Not Working

### ISSUE THREAD

**Issue by aicynide** [arnav-kr/miniTV#4] opened 2023-08-23 20:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Getting etror

### System Info

```markdown
- OS:
```

**Comment by arnav-kr** [comment] 2023-08-24 00:39
Could you provide more info, so that i can reproduce the issue, because it seems to work fine on my size

mention any specific error you're getting, what url you are testing on, your operating system etv

**Comment by arnav-kr** [comment] 2023-10-01 11:56
closing as no more info provided, reopen if you are here again

**Closed by arnav-kr** 2023-10-01 11:56 UTC
Labels: bug
